system_error: provide a thread safe stringification for Windows
Provide a strerror_r replacement for Windows.  This is needed to build
libc++ for Windows with threading.

llvm-svn=290851