Fixed handling of Objective-C properties to ensure that automatically generated setters/getters only get added to a class after explicitly declared (or synthesized) getters/setters had the chance to be added.  This eliminates conflicts creating errors of the form:
error: instance method '...' has incompatible result
types in different translation units ('X *' vs. 'id')

llvm-svn=157956