Fix a problem with objc foreach loop.  It turns out that objc mode changes for scoping to match C99 even when in C89 mode.  This patch fixes this (eliminating a "redefinition of thisKey" error), and also prevents non-sensical diagnostics in -pedantic mode like this:
t.m:7:8: warning: variable declaration in for loop is a C99-specific feature
  for (id thisKey in keys) ;
       ^

llvm-svn=69760